# Create a new list Without List Comprehension

In [ ]:
num = [3, 4, 9]
square = [] #blank list for new list

#looping for add value in list square
for i in num :
  square.append(i**2) 
print(square)

[9, 16, 81]

In [ ]:
fruit = ["aple", "melon", "kiwi", "banana"]
new_fruit = []

for i in fruit :
  if "a" in i :
    new_fruit.append(i)
print(new_fruit)

['aple', 'banana']

In [ ]:
x = [6, 8, 9]
y = [8, 10, 11]
less = []

#looking for value in list x,y if x > y
for i in x :
  for j in y :
    if i > j :
      less.append([i,j]) 
print(less)

[[9, 8]]

# Create a new list With List Comprehension

In [ ]:
num1 = [3, 4, 9]

square1 = [i**2 for i in num1] #add value from num1 list to square1
print(square1)

[9, 16, 81]

In [ ]:
fruit = ["aple", "melon", "kiwi", "banana"]

new_fruit1 = [i for i in fruit if "a" in i]
print(new_fruit1)

['aple', 'banana']

In [ ]:
x = [6, 8, 9]
y = [8, 10, 11]

less1 = [[i, j] for i in x for j in y if i > j]

print(less1)

[[9, 8]]